
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bd_admin
    username: devuser
    password: devpass
  jpa:
    hibernate:
      ddl-auto: validate # ⚠️ Nunca uses update/create en prod
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect